// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/Verifier.sol";

contract VerifierTest is Test {
    Verifier verifier;

    function setUp() public {
        verifier = new Verifier();
    }

    // Smoke test: deploying the verifier succeeds.
    function test_deploys() public view {
        assertTrue(address(verifier) != address(0));
    }

    // End-to-end test: verify a real Groth16 proof generated by `make calldata`.
    // The basic Noir circuit has one public input (the Poseidon2 hash result).
    // Reads artifacts/calldata/proof.hex and artifacts/calldata/inputs.txt.
    function test_verifyProof() public view {
        string memory proofHex = vm.readFile("../artifacts/calldata/proof.hex");
        bytes memory proofBytes = vm.parseBytes(proofHex);

        string memory inputsRaw = vm.readFile("../artifacts/calldata/inputs.txt");
        uint256 pubInput = vm.parseUint(inputsRaw);

        uint256[1] memory inputs;
        inputs[0] = pubInput;

        // verifyProof reverts on failure; if it returns we passed.
        verifier.verifyProof(proofBytes, inputs);
    }
}
